### ISSUE TITLE
Address Book 

### ISSUE THREAD

**Issue by megaluck** [ZencashOfficial/zencash-mobile#10]
Option to save the address's to a Address book and give it a alias, When sending the users would have the ability of puling out the address by just typing on the send field, auto-complete would be a nice feature to have there too.  Also in the main area where it shows the received and sent transactions, it would be nice to show the alias of from who we have received and who we sent it to ,  if its on our address-book

**Comment by kendricktan** [comment]
Feature was added on v0.0.6
https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.6
