### ISSUE TITLE
How to recover my Magnum Wallet ZEN address? 

### ISSUE THREAD

**Issue by Photoeventos** [ZencashOfficial/zencash-mobile#111]
How to retrieve Magnum Wallet address in ZEN Wallet?
I had a ZEN address created in Magnum Wallet, but that platform was already disabled, I downloaded ZEN Wallet Android, and placed the Mnemonic Phrase of recovery (12 words), and although the confirmation message (Wallet Recovered) appeared, the address did not appear nor the Neither balance, I must emphasize that the address created in Magnum Wallet was Verified in the Faucet https://getzen.cash/

Como recuperar dirección Magnum Wallet en ZEN Wallet?
Tenía una dirección ZEN creada en Magnum Wallet, pero esa plataforma ya quedó deshabilitada, descargué ZEN Wallet Android, y coloqué la Frase Nemónica de recuperación (12 palabras), y aunque apareció el mensaje de confirmación (Wallet Recovered) la dirección no apareció ni el saldo tampoco, debo destacar que la dirección creada en Mágnum Wallet estaba Verificada en el Faucet https://getzen.cash/

**Comment by Suksathian** [comment]
Thank you,So much,Sir.

**Comment by Nickam1** [comment]
Hi,
I've lost my cellular, and after getting the new one, I downloaded the horizon zen wallet.
I put the 24 words given before, unfortunately the wallet still writing 0.00000 zen.
So, how can I recuperate my coins?

**Comment by PowerVANO** [comment]
Hi @Photoeventos 

Even though you were able to restore your phrase from Magnum wallet to ZEN mobile wallet, they most likely use different address derivation paths.

Could you please check if you can restore your recovery phrase in their Magnum mobile wallet on Android? https://play.google.com/store/apps/details?id=com.magnum.wallet&hl=en_US&gl=US

Magnum also discontinued their wallet services: https://twitter.com/Magnum_Wallet/status/1333472916588081154

If you are still unable to recover your funds, I suggest to submit a request at our support portal: https://support.horizen.io/
