### ISSUE TITLE
Not working anymore. Not sending coins out

### ISSUE THREAD

**Issue by Jartsa823** [ZencashOfficial/zencash-mobile#143]
I withdrawal my coins 2 days ago but still no any confirmations, what is a problem. Why it is not send coins out anymore? Already sending email to support but no answer. I think it is dead wallet!
![Screenshot_20220412-084237_ZEN Wallet](https://user-images.githubusercontent.com/103482073/162888890-ea30baf9-252d-4973-941a-f2b0a74952f8.jpg)

**Comment by angievi** [comment]
Hi @Jartsa823 , Please make sure you use a fee of 0.0001 ZEN in any transactions you send using the wallet. If 0 ZEN is used for the fee transactions can take a very long time to confirm, or fail to confirm completely.

**Comment by Jartsa823** [comment]
Thanks for the answer. But I withdraw 0.0004008, as the picture shows, so hasn't a fee been charged for it, i.e. my wallet should have become 0.0003008? What is the "recommended" minimum withdwal?

**Comment by Jartsa823** [comment]
Coins received today in my wallet👍
