### ISSUE TITLE
French translation needed

### ISSUE THREAD

**Issue by aayanl** [ZencashOfficial/zencash-mobile#16]
^^ https://github.com/ZencashOfficial/zencash-mobile/tree/master/src/translations

**Comment by chem96** [comment]
hi
how to apply?
Is the french trad already assigned? If not, I'm in....

**Comment by darkkavenger** [comment]
Hey @aayanl I've already translated in french and provided a pull request. Can also take care of Italian. Cheers

**Comment by LukasBures** [comment]
#25
