### ISSUE TITLE
German Translation needed 

### ISSUE THREAD

**Issue by aayanl** [ZencashOfficial/zencash-mobile#18]
^^ https://github.com/ZencashOfficial/zencash-mobile/tree/master/src/translations

**Comment by andyvh** [comment]
Can I do this, or is someone else on it?

**Comment by aayanl** [comment]
no one submitted a PR for it yet :wink:

**Comment by andyvh** [comment]
Ok, I'll get on it then! Would you mind assigning it to me?

**Comment by andyvh** [comment]
Also, I note that the names for the translations are in English; is that how you'd like them, or should I name the German one Deutsch.js?

**Comment by aayanl** [comment]
Either is fine

**Comment by arnoobmeep** [comment]
export const GERMAN_TRANSLATION = {
  General: {
    loading: 'Lädt...',
    address: 'Adresse',
    privateKey: 'Private Zugangscode',
    cancel: 'Abbruch',    
    fees: 'Gebühren',
    version: 'Version',
    in: 'Eingehend',
    out: 'Ausgehend'
  },
  MainPage: {
    title: 'ZEN Brieftasche',
    value: 'Wert',        
    send: 'Senden',
    received: 'Erhalten',
    sent: 'Gesendet',    
    noTxFound: 'Keine Transaktions Historie gefunden.'
  },
  AddressInfoPage: {
    copyToClipboard: 'Zur Zwischenablage kopieren',
  },
  SendPage: {
    title: 'Sende ZEN',
    payTo: 'Bezahle an',
    amountToPay: 'zu bezahlender Betrag',
    balance: 'Kontostand',
    networkFee: 'Netzwerk Gebühr',
    slowTx: 'Langsame Tx',
    fastTx: 'Schnelle Tx',    
    from: 'Von',
    toAddress: 'Zu Adresse',
    amount: 'Betrag',    
    max: 'Max',    
    send: 'Sende',
    txSuccessful: 'Transaktion erfolgreich! Drücke hier um die Transaktion einzusehen.',
    confirmSend: 'I möchte diese ZEN senden',
    invalidAddress: 'Ungültige `Empfängeradresse` Nur transparente (öffentliche) Adressen werden derzeit unterstüzt.',
    invalidAmount: 'Ungültige `Betrag`.',
    invalidFee: 'Ungültige `Gebühren`. Versuche 0 :)',
    zeroAmount: 'Betrag muss größer 0 sein.',
    notEnoughZEN: 'Nicht genügend bestätigte ZEN im Benutzerkonto, um diese Transaktion auszuführen.',
    noCameraPermissions: 'Keine Kamera Berechtigungen. Die Funktion kann in den Einstellungen geändert werden.'
  },
  TxDetailPage:{
    txid: 'Transaktions Nummer',
    blockhash: 'Block Hash',
    blockheight: 'Block Höhe',
    confirmations: 'Bestätigungen',    
  },
  SettingsPage: {
    title: 'Einstellungen',    
    language: 'Sprache',
    currency: 'Währung',
    secretPhrase: 'Zeige die geheimen Zugangswörter',
    showPrivateKeys: 'Zeige den privaten Zugangscode',
    recoverExistingWallet: 'Wiederherstellung einer früheren Brieftasche',
    current: 'Derzeitige'
  },  
  SecretPhrasePage: {
    title: 'Geheime Zugangswörter'
  },
  ShowPrivateKeyPage: {
    title: 'Private Zugangscode'
  },
  RecoverExistingWalletPage: {
    title: 'Wiederherstellung Brieftasche',
    secretPhrase: 'Geheime Zugangswörter',
    textareaPlaceholder: 'Geheime Zugangswörter (min. 16 Buchstaben)',
    confirmUnderstand: 'Ich habe verstanden das bei der Wiederherstellung meine aktuelle Brieftasche gelöscht wird!',
    recover: 'Wiederherstellung'
  },
  AboutPage: {
    title: 'Über',
  },
  PinPage: {
    changePinTitle: 'PIN Ändern',
    newPinPageTitle: 'ZEN Brieftasche einstellen',
    verifyPinPageTitle: 'ZEN Brieftaschen Verifikation',
    setupNewPin: 'Neue PIN festlegen',
    reenterPin: 'PIN erneut eingeben',
    pinsNotSimilar: 'PINs stimmen nicht überein',
    invalidPin: 'Ungültige PIN',
    enterYourPin: 'PIN Eingabe'
  }
}

**Comment by arnoobmeep** [comment]
dont know how to push the file...

**Comment by LukasBures** [comment]
#23 has conflict with what I commited - based on @arnoobmeep translation.

**Comment by DropNib** [comment]
German here. I reworked the german translation to be gramatically and stylistically correct.
See #28
