### ISSUE TITLE
Please add Notifications

### ISSUE THREAD

**Issue by rubyxroot** [ZencashOfficial/zencash-mobile#34]
Hi, please add a notification whenever the user receive ZEN coin/s or have incoming transaction in their wallet. 

so that the user wont have to open the app every time and input the pin to  check if they got the coins.
 it will be more efficient and somewhat more secure to not have input the pin every time just to check if there is a new  transaction.

and also in the "copy address to clipboard" command, 
its better to have a notification or alert something like "copied to clipboard!"
to have a better User Experience. :-)

Thanks

**Comment by kendricktan** [comment]
Love the notification idea. Done :smile: 

The notification alert is however a different ball park. Due to the nature of the codebase, polling for information whilst in the background is going to be a bit tricky, probably a future release, but definitely not now.

**Comment by zennermac** [comment]
Hi there

Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

Regards
