### ISSUE TITLE
Can't transfer zencash

### ISSUE THREAD

**Issue by ivanzur** [ZencashOfficial/zencash-mobile#51]
Can't transfer zencash - even to own accounts.
v.0.0.6
Android 7.0
SM-G928

**Comment by kendricktan** [comment]
What error are you getting? Please attach the screenshot if possible.

**Comment by ivanzur** [comment]
Here is the screenshot:
![screenshot_20171026-135622](https://user-images.githubusercontent.com/33113143/32037560-6f2aef98-ba58-11e7-9771-04ad69f0d15c.png)

I had this same issue every time i tried to send funds even to my own wallet for two days.
Looked online for answer, saw your answer to someone else in another thread: something to do with updated certificates.
Tried it: removed cache, data and recovered wallet with passphrase - no success.
Tried removing the app and reinstalling it from Play Market: no success.

**Comment by kendricktan** [comment]
Unfortunately I can't reproduce the error.
If you want to transfer your ZEN out to bittrex/somewhere, you can use http://myzenwallet.io/ in the meantime.

**Comment by ivanzur** [comment]
But what is the error itself?

**Comment by kendricktan** [comment]
The error being thrown is a 400, which can happen with incorrect certificates.
There is a possibility that different variations of android can handle cert caching very differently, resulting in unpredictable and undesirable behaviors like so.

**Comment by ivanzur** [comment]
I see.
So, am I right to assume that private key from the mobile app can be imported into ZENCash Desktop Wallet too?

**Comment by kendricktan** [comment]
Yep you most certainly can

**Comment by ivanzur** [comment]
Alright. Xiexie ni de hezuo.
