### ISSUE TITLE
Can't recover wallet to Pixel XL

### ISSUE THREAD

**Issue by TimW584** [ZencashOfficial/zencash-mobile#54]
I originally installed Zen Wallet to a Galaxy S6. I just tried to recover that wallet on a Pixel XL phone. I cannot enter the entire secret phrase for the existing wallet, as the phrase input area stops accepting characters about half-way through the last secret word in the set.

**Comment by kendricktan** [comment]
Fixed in https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.8
