### ISSUE TITLE
No connection to backend since 7.11.2017

### ISSUE THREAD

**Issue by albabosh** [ZencashOfficial/zencash-mobile#55]
No connection to backend since 7.11.2017. Provider - Megafon mobile, Russia. Could it be a backend or a provider problem ?

**Comment by kendricktan** [comment]
Its likely that the backend it connects to is overwhelmed with the recent surge of users. I'll add an additional option for users to select their custom node.

**Comment by albabosh** [comment]
https://explorer.zensystem.io/ works fine for me, maybe there is another problem ?

**Comment by kendricktan** [comment]
Added support for custom insight endpoints https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.8
