### ISSUE TITLE
Still error 25 issue with Bittrex on v0.0.8

### ISSUE THREAD

**Issue by max1ne** [ZencashOfficial/zencash-mobile#56]
After update to v0.0.8 and change API insight to zenmine.pro still having same issue for sending zencash to Bitttex. I guess I will revert back to v0.0.5 which working fine for this specific issue...

**Comment by aayanl** [comment]
Increase your tx fee

**Comment by max1ne** [comment]
Respecfully, I dont think the issue lies on the tx fee. I've tried to max the fee up to 0.001 but still presented with same error message.

**Comment by kendricktan** [comment]
Hi,

What version of and flavour and Android are you running?
Can you state the steps to reproduce the error?

**Comment by max1ne** [comment]
Android 7.0 - Security Patch Level: 1 Aug 2017
Galaxy S7 Edge (SM-G935FD)
Kernel version: 3.18.14011104523 (non-rooted)

Steps:
0. Change API insight to zenmine.pro
1. Paste the destination address (or select from contact). Both produced same issue.
2. Select Max amount
3. Tick I want to Send this ZEN (regardless keep default fee, increase half of slide-bar or increase fee to max all produced same issue)
4. Click Send
Android 7.0 - Security Patch Level: 1 Aug 2017
Galaxy S7 Edge (SM-G935FD)
Kernel version: 3.18.14011104523 (non-rooted)
Normal Step:
0. Change API insight to zenmine.pro
1. Paste the destination address (or select from contact). Both produced same issue.
2. Select Max amount
3. Tick I want to Send this ZEN (regardless keep default fee, increase half of slide-bar or increase fee to max all produced same issue)
4. Click Send
Android 7.0 - Security Patch Level: 1 Aug 2017
Galaxy S7 Edge (SM-G935FD)
Kernel version: 3.18.14011104523 (non-rooted)

Steps:
0. Change API insight to zenmine.pro
1. Paste the destination address (or select from contact). Both produced same issue.
2. Select Max amount
3. Tick I want to Send this ZEN (regardless keep default fee, increase half of slide-bar or increase fee to max all produced same issue)
4. Click Send
Android 7.0 - Security Patch Level: 1 Aug 2017
Galaxy S7 Edge (SM-G935FD)
Kernel version: 3.18.14011104523 (non-rooted)
Normal Step:
0. Change API insight to zenmine.pro
1. Paste the destination address (or select from contact). Both produced same issue.
2. Select Max amount
3. Tick I want to Send this ZEN (regardless keep default fee, increase half of slide-bar or increase fee to max all produced same issue)
4. Click Send

**Comment by iamniks** [comment]
Issue is still there. Steps above

**Comment by kendricktan** [comment]
Can you try https://forum.zensystem.io/t/resolving-zen-wallet-error-on-sending/773/1

**Comment by loopinitcrypto** [comment]
Tried to change to all of those insight api and still I get the error.
Also tried using Max fees on all of the transactions all give same error.

"Alert"
"Not enough confirmed ZEN in account to perform transaction.

Highly inconvenient please fix.
