### ISSUE TITLE
My transaction has benn stuck for 2hr. 

### ISSUE THREAD

**Issue by myominaung92** [ZencashOfficial/zencash-mobile#60]
Hello bro
I send zen from zen wallet 0.0.8 to exchange. It appear transaction history in application and I found the transaction in zen explorer. but it is in unconfirmed status even I set enough fee in this transaction. 

Transaction d7d748987a0f2ba7f08d891ba2e335e63a17bec2bf6689e338821db4cbf84d98

Summary

Size	302 (bytes)
Fee Rate	0.0002496026490066225 zen per kB
Received Time	Dec 6, 2017 8:54:22 PM
Mined Time	N/A
Included in Block	Unconfirmed

**Comment by myominaung92** [comment]
it has been stuck for 2hr not included in any block

https://explorer.zensystem.io/tx/d7d748987a0f2ba7f08d891ba2e335e63a17bec2bf6689e338821db4cbf84d98

**Comment by myominaung92** [comment]
![screenshot_2017-12-06-20-54-34-597_com android chrome](https://user-images.githubusercontent.com/22629658/33666704-3c1585b4-dac9-11e7-8ee1-11efe0e131aa.png)

**Comment by kendricktan** [comment]
Yo, try using v0.0.12, it has dynamic fees

**Comment by mikeone56** [comment]
Hi i have the same problem a unconfirmed transactions for over 10 hours how do i fix this.

**Comment by zennermac** [comment]
The transaction fee logic was changed in the last release to ensure fees are set correctly to avoid any stuck transactions due to low fees.
