### ISSUE TITLE
QR and clipboard

### ISSUE THREAD

**Issue by ponta9** [ZencashOfficial/zencash-mobile#61]
Would be nice being able to add contacts with QR codes. Maybe even being able to name yourself in settings so if someone adds you with QR the name  gets filled.

**Comment by ponta9** [comment]
Also being able to copy adresses and Transactions from history

**Comment by zennermac** [comment]
Hi there

Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

Regards
