### ISSUE TITLE
Input PIN after send button

### ISSUE THREAD

**Issue by rubyxroot** [ZencashOfficial/zencash-mobile#62]
Hi, 

I think its better that, after you press the send button 
it will ask you for your PIN again?

just for added security.. 

because sometimes if you switch apps or pressed the home button. Wallet is still open and unlocked. and sometimes forgot that its still open and unlocked.

**Comment by zennermac** [comment]
Hi there

Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

Regards
