### ISSUE TITLE
Bug wallet 

### ISSUE THREAD

**Issue by 2pac1978** [ZencashOfficial/zencash-mobile#66]
hello I transferred 1.05 on cryptopia but no transfer is done ... on my wallet my balance is still present but I can not do anything else .... the transaction info are: bbfabdc51448e6dd77468438290ee647c97ca6db8210a2f76c42fd1e1290bb40 but no other information ? I have version 0.0.12 thank you for doing the necessary ....

**Comment by s2545012** [comment]
很意外吧，我说的中文，我想告诉你，看不懂英文还愿意买数字货币的人比看得懂的要多，受限于语言而不能加入这个圈子太可惜了，区块链技术将为世界附能，为什么要让语言束缚它呢，密钥非得是英文字母吗，这个网站没有app吗，你们要做的是面向世界的应用，要用区块链技术把每一个人连接起来，日后发明量子纠缠技术改变信息传递方式的时候，区块链技术才真正的强大起来，不要问我是谁，我来自未来
