### ISSUE TITLE
When we will have iOS Wallet

### ISSUE THREAD

**Issue by zay7sev** [ZencashOfficial/zencash-mobile#67]
Hello there.
Since it was mentioned in one of the early released versions I would like to ask when the iOS users will receive version of the wallet?

**Comment by tarrenj** [comment]
We're just waiting on our Apple Developer Program account to be processed, the App is finished.

**Comment by DatDraggy** [comment]
Any updates? Couldn't find anything else about it. I'd like to add it to my zencash help bot for the telegram group.

**Comment by Ahmen** [comment]
I am unable to earn from faucet. The error I get is invalid wallet error. Please help

**Comment by psyraxaus** [comment]
@Ahmen unfortunately that error from the faucet is a misnomer, as this error is reported when the faucet is out of zen
