### ISSUE TITLE
node-pre-gyp http 404 error

### ISSUE THREAD

**Issue by greerso** [ZencashOfficial/zencash-mobile#68]
build for ios on MacOS 10.13 npm version 5.7.1, node 9.8.0 get error:

`node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz`

when executing `yarn install`

resolved with `npm install -g node-gyp`

But then `(node:44518) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'`

when executing (node:44518) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'

**Comment by kendricktan** [comment]
Only Node v6.11.X is supported unfortunately :slightly_frowning_face:

**Comment by greerso** [comment]
Thanks, I misunderstood that on the readme as >6.11.  I'll roll back and try again.

**Comment by greerso** [comment]
Installed Node v6.11.2 with `nvm install v6.11.2` But still have issues when executing `cordova platform add ios`:

```
WARNING in ./node_modules/natural/lib/natural/wordnet/wordnet.js
Module not found: Error: Can't resolve 'WNdb'
```
and
```
WARNING in ./node_modules/sylvester/lib/node-sylvester/matrix.js
Module not found: Error: Can't resolve 'lapack'
```

**Comment by greerso** [comment]
I got it to build  by using an old version of Cordova.  If you want to build this you need `nvm install v6.11.5` and `npm install -g cordova@7.1.0`
