### ISSUE TITLE
Can't transfer zencash from android wallet

### ISSUE THREAD

**Issue by shell21Mo** [ZencashOfficial/zencash-mobile#69]
I can access wallet but can't transfer zencash.  Im getting alert code....GET failure: ()

**Comment by kendricktan** [comment]
Have you tried a different API endpoint?

**Comment by zennermac** [comment]
The api endpoints were updated in the last release

Also a point to note regarding this wallet is that
Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates here.

Regards
