### ISSUE TITLE
Attempted sending of unshielded coinbase UTXO

### ISSUE THREAD

**Issue by tarrenj** [ZencashOfficial/zencash-mobile#70]
It seems UTXOs are selected in a FILO fashion, and there is no verification that the coins have been unshielded , so users are unable to spend from an address after it receives a coinbase UTXO.

Also see [Arizen issue](https://github.com/ZencashOfficial/arizen/issues/318).

**Comment by zennermac** [comment]
Hey Jake

As your aware Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

So I'm gonna close this out now

Regards
