### ISSUE TITLE
Error sending transaction when ZEN amount is partially edited. 

### ISSUE THREAD

**Issue by Toadbully** [ZencashOfficial/zencash-mobile#71]
That's a bit of weird title I know.

When sending a transaction to an exchange I noticed that if I left the default 1 ZEN in the amount box and added a .5 to leave 1.5 in the box the app produces an error. I tried the above method another 2 times and produced the error. 

I was able to make the transaction after removing the 1 and typing 1.5 in full.

I have just tried sending a transaction using the first method of just editing the amount box to get a copy of the error for here and the transaction was successful. 

Coz I'm on holiday and didnt have my Dev hat on I am unable to provide a copy of the error.

Because I partially put my Dev hat back on I will add that the error was happening on my  first ever send transaction from the app. 

From a hazy holiday memory the message was titled Transaction failed. And had a dump of what looked like json/javascript.

**Comment by zennermac** [comment]
Hey there

Thanks for reporting.

Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

Regards
