### ISSUE TITLE
Compile trouble

### ISSUE THREAD

**Issue by bitzec** [ZencashOfficial/zencash-mobile#91]
Can i have a clear   guide to compile on ubuntu 16 lts  please

**Comment by zennermac** [comment]
Hi there,
Personally, I would be using a newer release of ubuntu to be attempting this.
18.04 for instance.
The guide for the build is pretty straight forward, although you will likely need to install Gradle also.
Can you explain the exact errors/issues you are facing?

**Comment by bitcoinbzc** [comment]
@ ./node_modules/sylvester/lib/node-sylvester/matrix.js 873:8-25                                                   
 @ ./node_modules/sylvester/lib/node-sylvester/index.js                                                             
 @ ./node_modules/apparatus/lib/apparatus/clusterer/kmeans.js                                                       
 @ ./node_modules/apparatus/lib/apparatus/index.js                                                                  
 @ ./node_modules/natural/lib/natural/classifiers/logistic_regression_classifier.js                                 
 @ ./node_modules/natural/lib/natural/index.js                                                                      
 @ ./node_modules/sentencer/index.js                                                                                
 @ ./src/containers/SetupPage.js                                                                                    
 @ ./src/containers/App.js                                                                                          
 @ ./src/index.js                                                                                                   
 @ multi ./src/index.js                                                                                             
ANDROID_HOME=/usr/lib/android-sdk/
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
Requirements check failed for JDK 1.8 or greater

**Comment by zennermac** [comment]
I always use the official Oracle JDK when performing our builds.
I would remove OpenJDK and install the official Oracle JDK 1.8

**Comment by zennermac** [comment]
Can you please let me know the exact commands you are executing in order.
Also are you building for Android - this is what I am assuming.

**Comment by bitcoinbzc** [comment]
cordova run android
cordova build --release android

**Comment by bitzec** [comment]
Solved this problem ... now have to solve the android-sdk  licenses problem
