### ISSUE TITLE
Solved this problem by installing jdk 8 ... now have to solve the android-sdk  licenses problem

### ISSUE THREAD

**Issue by bitzec** [ZencashOfficial/zencash-mobile#92]
Solved this problem ... now have to solve the android-sdk  licenses problem

_Originally posted by @bitzec in https://github.com/ZencashOfficial/zencash-mobile/issues/91#issuecomment-522264663_

**Comment by zennermac** [comment]
So what license problem are you seeing?

**Comment by bitzec** [comment]
Moved to android-studio

It works now ...

Thanks for reply

Regards

zennermac <notifications@github.com> schrieb am Mi., 21. Aug. 2019, 19:50:
