### ISSUE TITLE
Error Reading Amount from QR Code

### ISSUE THREAD

**Issue by styp152** [ZencashOfficial/zencash-mobile#93]
i am working with a payment processor system which recently added support for ZEN, doing some tests with the ZEN mobile-wallet, our qr code contains the address and the amount for payment but the zen wallet doesn't take the amount, but the coinomi wallet does.

![image](https://user-images.githubusercontent.com/241622/66963235-d2624080-f038-11e9-94c0-ace713711011.png)

![image](https://user-images.githubusercontent.com/241622/66963251-da21e500-f038-11e9-90bf-f4a4227156d5.png)

Adicional the data inside the qr code is:

```
horizen:znf8NFf2ryXVvZouBdBCy4b6rN6uFHuEs9k?amount=0.01815714&label=Pay+in+Panda-BTM+by+Xpay
```

And coinomi read this qr like this 

![image](https://user-images.githubusercontent.com/241622/66963346-12292800-f039-11e9-84a8-31721907e5e5.png)

**Comment by Lesibajo** [comment]
My zen wallet doesn't reflect my mined amount, even though the horizen faucet do send my earnings through, this has been since the 1st of this month, up until today. Assistance please

**Comment by zennermac** [comment]
@Lesibajo This is a known issue with existing pricing API. We're migrating ATM to a new mechanism. Releases will be announced/published in the usual channels.

**Comment by Lesibajo** [comment]
Hello, Lesiba Dikgale here,
I'm would like to know as I'm in South Africa, what is the best wallet to
download for my Zen withdrawal.
My present wallet, which is Luno and also blockchain doesn't support zen
withdrawal. This is if I will need to withdraw for personal use. Assistance
in this matter will be greatly appreciated. Regards. Lesiba

**Comment by uanl979** [comment]
@Lesibajo 

Please take a look at our [supported wallets](https://www.horizen.global/wallets/), you can choose between our official wallets and our third party wallets. I´ll list you my personal recommendations:

- Desktop: I will recommend using our flagship wallet [Sphere by Horizen](https://www.horizen.global/spherebyhorizen/) 
- Android: I recommend you our official[ Android wallet](https://play.google.com/store/apps/details?id=io.zensystem.zencashwallet).
- iOS: [MyZenWallet](https://myzenwallet.io/) or take a look at our third party wallets offering support to apple mobile devices. :)

If you have extra questions, I could provide you further assistance on your inquiry through our support system. I can create a support ticket on your behalf, I just require an email :)

**Comment by uanl979** [comment]
hey @styp152 

We are aware of this issue, Coinomi's and ZEN android wallet have different logic to handle the QR, hence the difference in functionality. 

Unfortunately, mobile wallet is in maintenance mode only. New features will not be added at this time.

I'll keep you posted if something new comes up.

Regards

**Comment by uanl979** [comment]
Closing this issue, feel free to raise a support ticket if needed.

**Comment by Ulzpops** [comment]
My wallet is not working again, i can't view my balance, always showing No connection while am connected, plz help me fix it, 
You can reach me @ stallionsnowking@gmail.com
![Screenshot_20211115_174144](https://user-images.githubusercontent.com/89754690/141820230-97f31360-4ecf-488a-a2ac-410465367243.jpg)
