### ISSUE TITLE
Desktop and Android wallets not in syns

### ISSUE THREAD

**Issue by AndreiHere** [ZencashOfficial/zencash-mobile#97]
Hi team

I'm trying to recover my wallet on my Android device using the backup phrase used on my Mac. The wallet recovers with completely different addresses and 0 balance. I'm trying to keep the same address/wallet on multiple devices.

**Comment by uanl979** [comment]
Hey @AndreiHere 

The backup phrases seeds are not the compatible on both platforms. 

- Android Wallet uses a 12 word seed phrase 
- Sphere uses a 24 word seed phrase

This is the reason why you were not successful on restoring a seed from a wallet in sphere into an android and vice-versa.

**Comment by AndreiHere** [comment]
Thank you

**Comment by uanl979** [comment]
Remember that for every doubt or support, you can contact us at 
support.horizen.global

I'll close this issue. 
Regards
